name: update-protofiles
description: Update protofiles submodule

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      with:
        submodules: 'recursive'
      uses: actions/checkout@v2

    - name: Run pull-protofile-submodule.sh
      shell: bash
      env:
        SUBMODULE_PATH: proto-submodule
        SUBMODULE_URL: https://github.com/mjpowersjr/cicd-test-protos
        CHECKOUT_TARGET: main
      run: scripts/update-submodule.sh $SUBMODULE_PATH $SUBMODULE_URL $CHECKOUT_TARGET
