name: update-protofiles
description: Update protofiles submodule

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git credentials
      shell: bash
      run: |
        git config --global user.email "noreply@github.com"
        git config --global user.name "GitHub Actions"

    - name: Run pull-protofile-submodule.sh
      shell: bash
      env:
        SUBMODULE_PATH: proto-submodule
        SUBMODULE_URL: https://github.com/mjpowersjr/cicd-test-protos
        CHECKOUT_TARGET: main
      run: scripts/update-submodule.sh $SUBMODULE_PATH $SUBMODULE_URL $CHECKOUT_TARGET

    # - name: Check exit code
    #   shell: bash
    #   run: exit ${{ steps.update-protos.outcome }}
