name: update-protofiles
description: Update protofiles submodule

inputs:
  submodule_path:
    description: 'A path to the submodule directory'
    required: true
  submodule_url:
    description: 'A URL to the submodule repository'
    required: true
  checkout_target:
    description: 'A branch or tag to checkout'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Checkout code
      with:
        submodules: 'recursive'
      uses: actions/checkout@v2

    - name: Run pull-protofile-submodule.sh
      shell: bash
      env:
        SUBMODULE_PATH: ${{ inputs.submodule_path }}
        SUBMODULE_URL: ${{ inputs.submodule_url }}
        CHECKOUT_TARGET: ${{ inputs.checkout_target }}
      run: scripts/update-submodule.sh $SUBMODULE_PATH $SUBMODULE_URL $CHECKOUT_TARGET
