name: generate-code
description: Generate code from protofiles

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies with Yarn
      shell: bash
      run: yarn install

    - name: Run build-generate-code.sh
      shell: bash
      env:
        SRC_DIR: proto-submodule
        OUT_DIR: src/generated
      run: scripts/build-generate-code.sh $SRC_DIR $OUT_DIR

    - name: Check exit code
      shell: bash
      run: exit ${{ steps.generate-code.outcome }}
