name: perform-release
description: Perform a release

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config --json cacheFolder)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ fromJson(steps.yarn-cache-dir-path.outputs.dir).effective }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies with Yarn
      shell: bash
      run: yarn install

    - name: Build
      shell: bash
      run: yarn build
