name: Release Workflow

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: scripts/build.sh

      - name: Check for new version
        id: check-version
        run: |
          npm install -g beachball
          beachball change --path packages/my-package --no-push --no-publish

      - name: Publish new version
        if: steps.check-version.outputs.version_changed == 'true'
        run: |
          npm install -g @actions/github
          node publish.js
